# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 21:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, db_tablespace=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(db_tablespace=None, max_length=255, unique=True)),
                ('game_url', models.URLField(db_tablespace=None)),
                ('game_price', models.FloatField(db_tablespace=None)),
                ('game_copies_sold', models.PositiveIntegerField(db_tablespace=None, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('developer', models.BooleanField(db_tablespace=None, default=True)),
                ('active', models.BooleanField(db_tablespace=None, default=False)),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, db_tablespace=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(db_tablespace=None, default=0)),
                ('game', models.ForeignKey(db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, to='hello.Game')),
                ('player', models.ForeignKey(db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_developer',
            field=models.ForeignKey(db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
