# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_copies_sold',
            new_name='game_sales',
        ),
    ]
