# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0006_partial'),
        ('admin', '0002_logentry_remove_auto_add'),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
