# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0002_auto_20170420_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, db_tablespace=None, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.BooleanField(db_tablespace=None, default=False)),
                ('activated', models.BooleanField(db_tablespace=None, default=False)),
                ('user', models.OneToOneField(db_tablespace=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
