# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170413_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
    ]
