# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-27 08:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20170423_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 27, 8, 27, 35, 34812, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
