# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_remove_player_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activated',
            field=models.BooleanField(db_tablespace=None, default=False),
        ),
    ]
