# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-22 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20170422_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
